### ISSUE TITLE
在错误的使用指令后会先发送发生未知错误才开始提示

### ISSUE THREAD

**Issue by axlmly** [KIRA2ZERO/koishi-plugin-pool-simulator#2]
报错如下
command poolmanager.draw 
                        TypeError: Cannot read properties of undefined (reading 'goodsList')
                            at /root/koimux_bot/node_modules/koishi-plugin-pool-simulator/lib/index.js:228:36
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Command.<anonymous> (/root/koimux_bot/node_modules/koishi-plugin-pool-simulator/lib/index.js:218:9)
                            at async Array.<anonymous> (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:1656:14)
                            at async _Command.execute (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:1671:22)
                            at async /root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:2320:22
                            at async _Session.withScope (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:2188:22)
                            at async next (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:844:16)
                            at async next (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:844:16)
                            at async next (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:844:16)

![IMG_20230911_120357.jpg](https://github.com/KIRA2ZERO/koishi-plugin-pool-simulator/assets/41771421/30fa850f-fff0-4768-b3d6-a46b162b9900)

**Comment by KIRA2ZERO** [comment]
这个知道原因了 但是这样也没什么影响吧 反正就是错误的使用会有的

**Comment by axlmly** [comment]
> 这个知道原因了 但是这样也没什么影响吧 反正就是错误的使用会有的

主要是看着不适古怪，错误使用看群友发生的次数还挺多的。以及快捷调用是否能改成开关式，偶尔误触观感也不是很好

**Comment by KIRA2ZERO** [comment]
已修复
